/*
 * Copyright (c) 2019, Arm Limited. All rights reserved.
 * Copyright (c) 2024 STMicroelectronics. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */
#include "region_defs.h"
#include "mcuboot_config/mcuboot_config.h"

#define _HEX(n) 0x##n
#define HEX(n)  _HEX(n)

/* Enumeration that is used by the postbuild script
 * for correct binary generation when nested macros are used
 */

enum image_attributes
{
  RE_FLASH_AREA_SCRATCH_OFFSET = FLASH_AREA_SCRATCH_OFFSET,
  RE_FLASH_AREA_SCRATCH_SIZE = FLASH_AREA_SCRATCH_SIZE,
  /* Image size */
  RE_CODE_IMAGE_SIZE = (FLASH_PARTITION_SIZE),

  /* Image slot offset */
  RE_AREA_0_OFFSET = (FLASH_AREA_0_OFFSET),
#if (MCUBOOT_DATA_IMAGE_NUMBER == 1)
  RE_AREA_5_OFFSET = (FLASH_AREA_5_OFFSET),
#else
  RE_AREA_5_OFFSET = (0x0),
#endif /* (MCUBOOT_DATA_IMAGE_NUMBER == 1) */
#if defined(MCUBOOT_PRIMARY_ONLY)
  RE_AREA_2_OFFSET = (0x0),
#else
  RE_AREA_2_OFFSET = (FLASH_AREA_2_OFFSET),
#endif /* defined(MCUBOOT_PRIMARY_ONLY) */
#if defined(MCUBOOT_PRIMARY_ONLY) || (MCUBOOT_DATA_IMAGE_NUMBER == 0)
  RE_AREA_7_OFFSET = (0x0),
#else
  RE_AREA_7_OFFSET = (FLASH_AREA_7_OFFSET),
#endif /* defined(MCUBOOT_PRIMARY_ONLY) || (MCUBOOT_DATA_IMAGE_NUMBER == 0) */

  /* Application code start offset */
  RE_IMAGE_PRIMARY_AREA_OFFSET = (IMAGE_PRIMARY_AREA_OFFSET),

  /* Data image */
#if (MCUBOOT_DATA_IMAGE_NUMBER == 1)
  RE_DATA_IMAGE_NUMBER = (HEX(MCUBOOT_DATA_IMAGE_NUMBER)),
  RE_DATA_IMAGE_ADDRESS = (FLASH_BASE_ADDRESS + FLASH_AREA_5_OFFSET),
  RE_DATA_IMAGE_SIZE = (FLASH_DATA_PARTITION_SIZE),
  RE_DATA_OFFSET = (DATA_IMAGE_DATA_OFFSET),
  RE_DATA_SIZE = (DATA_IMAGE_DATA_SIZE),
#else
  RE_DATA_IMAGE_NUMBER = (0x0),
  RE_DATA_IMAGE_ADDRESS = (0x0),
  RE_DATA_IMAGE_SIZE = (0x0),
  RE_DATA_OFFSET = (0x0),
  RE_DATA_SIZE = (0x0),
  RE_DATA_IMAGE_PARTITION_OFFSET = (0x0),
  RE_DATA_IMAGE_PARTITION_ADDRESS = (0x0),
#endif /* (MCUBOOT_DATA_IMAGE_NUMBER == 1) */

  /* Option bytes */
  RE_BL2_WRP_END = (FLASH_AREA_PERSO_OFFSET + FLASH_AREA_PERSO_SIZE - 0x1),
  RE_BL2_HDP_END = (FLASH_AREA_SCRATCH_OFFSET + FLASH_AREA_SCRATCH_SIZE - 0x1),

  /* Loader */
#if defined(MCUBOOT_EXT_LOADER)
  RE_LOADER_CODE_OFFSET = (FLASH_AREA_LOADER_OFFSET),
  RE_LOADER_CODE_START = (LOADER_CODE_START),
  RE_LOADER_CODE_SIZE = (LOADER_CODE_SIZE),
  RE_LOADER = 1,

  RE_LOADER_WRP_END = (FLASH_AREA_LOADER_OFFSET + LOADER_CODE_SIZE - 0x1),
#else
  RE_LOADER_CODE_OFFSET = (0x0),
  RE_LOADER_CODE_START = (0x0),
  RE_LOADER_CODE_SIZE = (0x0),
  RE_LOADER = 0,

  RE_LOADER_WRP_END = (0x0),
#endif /* defined(MCUBOOT_EXT_LOADER) */

  /* Download slots */
#if defined(MCUBOOT_PRIMARY_ONLY)
  RE_PRIMARY_ONLY = (0x1),
  RE_IMAGE_PARTITION_OFFSET = (FLASH_AREA_0_OFFSET),
  RE_IMAGE_PARTITION_ADDRESS = (FLASH_BASE_ADDRESS + FLASH_AREA_0_OFFSET),
#if (MCUBOOT_DATA_IMAGE_NUMBER == 1)
  RE_DATA_IMAGE_PARTITION_OFFSET = (FLASH_AREA_5_OFFSET),
  RE_DATA_IMAGE_PARTITION_ADDRESS = (FLASH_BASE_ADDRESS + FLASH_AREA_5_OFFSET),
#endif /* (MCUBOOT_DATA_IMAGE_NUMBER == 1) */
#else
  RE_PRIMARY_ONLY = (0x0),
  RE_IMAGE_PARTITION_OFFSET = (FLASH_AREA_2_OFFSET),
  RE_IMAGE_PARTITION_ADDRESS = (FLASH_BASE_ADDRESS + FLASH_AREA_2_OFFSET),
#if (MCUBOOT_DATA_IMAGE_NUMBER == 1)
  RE_DATA_IMAGE_PARTITION_OFFSET = (FLASH_AREA_7_OFFSET),
  RE_DATA_IMAGE_PARTITION_ADDRESS = (FLASH_BASE_ADDRESS + FLASH_AREA_7_OFFSET),
#endif /* (MCUBOOT_DATA_IMAGE_NUMBER == 1) */
#endif /* defined(MCUBOOT_PRIMARY_ONLY) */

#if defined(MCUBOOT_ENC_IMAGES)
  RE_ENCRYPTION = (0x1),
#else
  RE_ENCRYPTION = (0x0),
#endif /* defined(MCUBOOT_ENC_IMAGES) */

#if defined(MCUBOOT_OVERWRITE_ONLY)
  RE_OVER_WRITE = (0x1),
#else
  RE_OVER_WRITE = (0x0),
#endif /* defined(MCUBOOT_OVERWRITE_ONLY) */
};
